### ISSUE TITLE
Take a look at snyk.io

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#25]
They are a commercial company but provide some open source tools that perform static code analysis in order to identify known security vulnerabilities. Currently we recommend using `[nsp](https://github.com/bucharest-gold/entente/blob/master/GUIDELINES.md#security)` for this. We should determine if there is any reason to consider snyk over our current process.

Snyk has an open source component: https://github.com/Snyk/snyk
Vulnerabilities DB: https://github.com/Snyk/vulndb

**Comment by lance** [comment]
I think this is pretty much done, right @helio-frota? I know you were doing some stuff here as well, what's your status on this?

**Comment by helio-frota** [comment]
well, I did not much on this.
btw I prefer nsp because :
- works fine.
- Now we have amount of project to take care using it
- This scares a bit:

`
If you selected to, Snyk will include snyk test as part of your npm test command, so if there are new vulnerabilities in the future, your CI will fail protecting you from introducing vulnerabilities to production.
`

**Comment by helio-frota** [comment]
I mean we have to care on our CI stuff ^ and custom tape usage etc... IMO not a really good idea to use

**Comment by lance** [comment]
Closing for now. Unless we see a more compelling need to use it, snyk.io isn't really right for us now.
