### ISSUE TITLE
npm-init.js should be smarter about the github username

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#47]
My original suggestion was to use `$USER`, but that wasn't ideal because it's just the username on your local machine which may not match your github username.

Then @helio-frota suggested using `git config user.name` which is a good start, but also not ideal for the same reason, and also because in most git documentation, the `user.name` configuration value is a full name, like "Lance Ball".

**Comment by lholmquist** [comment]
This is the code for what the default thing does,    https://github.com/npm/init-package-json/blob/master/default-input.js#L182

perhaps we do a little copy/paste :)

**Comment by lance** [comment]
@lholmquist There might have been a race condition between your comment and my push. How do you feel about the prompt I added?

Also, we should probably add another issue to entente about using any existing package.json. By default, `npm init` will use any values it finds in an existing package.json as the defaults.

**Comment by lholmquist** [comment]
@lance the default for `npm init` is to only create this "repository" section if the directory running npm init is under git control.   We created it no matter what, which is probably ok, since most, if not all, packages we create will be on github.

I think the prompt works,  but it is sort of a downgrade from what the default behavior did.  However, i don't think we can use that default code to get the git user if the user hasn't done the git init/add remote yet since that code looks for the "origin" remote

the other thing is that when i do a `npm init -y` i get "Lucas Holmquist" as my git user, but i don't think we can really do anything about that, since we don't prompt

If we wanted to get crazy, we could prompt the user for there git username only if we don't find it in the `.git` folder(like the default code)

**Comment by lance** [comment]
Yeah - I noticed that problem with the git user using `-y`. I think we should go crazy. I'll look at it.

**Comment by helio-frota** [comment]
Folks I don't know if has something different from linux and mac.
I have only one username : 'helio-frota' here on my machine inside ~/.gitconfig file.

After run this command on entente repository:

`git log --pretty='%cn %an' -n3`

> cn - committer name
> an - author name

It returns:

```
Lucas Holmquist Lucas Holmquist
Lucas Holmquist Lucas Holmquist
Lance Ball Lance Ball
```

Also I have no `GIT_COMMITTER_NAME` and no `GIT_AUTHOR_NAME` environment variables exported.

lance and lholmquist are your computer usernames right ? [$USER]

**Comment by lholmquist** [comment]
@helio-frota i think we need to look at what the "origin remote" is for the correct github user,

**Comment by lance** [comment]
@helio-frota for the `git.config` values, all of the documentation I have seen recommends using your real, full name for `user.name`. See https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup and https://help.github.com/articles/setting-your-username-in-git/.

Take a look at the code @lholmquist referenced above https://github.com/npm/init-package-json/blob/master/default-input.js#L182-L202. This code is reading `[projectdir]/.git/config`, then parsing the URL for the `origin` repository, and using the username found in the path there. I believe this is what @lholmquist is suggesting we do, and I tend to agree. This should be more accurate in the long run, I believe.

**Comment by helio-frota** [comment]
@lholmquist @lance got it ! Thanks!

**Comment by helio-frota** [comment]
Instructions for the functional tests I did are on the git comment:
https://github.com/bucharest-gold/entente/commit/c75d9ecbc94bebadf301d79cd96b1cf53841de1a

**Comment by lance** [comment]
@helio-frota so can this be closed?

**Comment by helio-frota** [comment]
@lance Yes.
